title:   Mark Noble
logo: /assets/Circle_Headshot.png
description: mark.d.noble505@gmail.com  www.linkedin.com/in/marknoble01/ - [Jump to Business Statistics Project](#business-statistics-project)
theme: jekyll-theme-minimal

